# Generated by Django 5.2.6 on 2025-09-26 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('foto', models.BinaryField()),
                ('status', models.BooleanField(default=True)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('data_nascimento', models.DateField()),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='tenants.tenant')),
            ],
        ),
    ]
