# Generated by Django 5.2.6 on 2025-09-26 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tenant_id',
            new_name='tenant',
        ),
    ]
