# Generated by Django 5.2.6 on 2025-09-26 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tenants.tenant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_authored', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tenants.tenant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_authored', to='accounts.user')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fead.post')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('reaction_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='fead.comment')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='tenants.tenant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions_authored', to='accounts.user')),
            ],
        ),
    ]
