# Generated by Django 5.2.6 on 2025-09-26 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
