# Generated by Django 5.2.6 on 2025-09-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fead', '0002_rename_post_id_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='tipo',
            field=models.CharField(choices=[(1, 'Curtir'), (2, 'Amei'), (3, 'Haha'), (4, 'Triste'), (5, 'Raiva')]),
        ),
    ]
