# Generated by Django 5.2.6 on 2025-09-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fead', '0003_alter_reaction_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
